name: Vue.js build & deploy

on:
  push:
    branches: [ "master" ]

jobs:
  vue-build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build Vue.js application
      run: npm run build

    - name: Build and tag Docker image
      run: |
        docker build -t my-vue-app .
        docker tag my-vue-app my-vue-app:latest

    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
